// <auto-generated />
namespace CarDealership.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_Vechicle_Picture_URL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Vechicle_Picture_URL));
        
        string IMigrationMetadata.Id
        {
            get { return "201801310548039_added_Vechicle_Picture_URL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
