// <auto-generated />
namespace CarDealership.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Vehicle_Pictures_Into_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Vehicle_Pictures_Into_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201801042131234_added_Vehicle_Pictures_Into_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
